languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
enableEmoji = true
publishDir = "docs"

theme = "almeida-cv"
disableKinds = ["page", "section", "taxonomy", "term", "RSS", "sitemap"]

baseURL = "https://alexrgreenwood.github.io/me/"
title = "Alex Greenwood - CV"
#googleAnalytics = ""

[params]
enableMetaTags = true
colorLight = "#fff"
colorDark = "#666"
colorPageBackground = "#ddd"
colorPrimary = "#000068"
colorSecondary = "#000068"
colorIconPrimary = "#fff"
colorIconBackground = "#465484"
colorRightColumnBackground = "#f5f5f5"
colorRightColumnHeadingText = "#666"
colorRightColumnBodyText = "#666"
colorRightColumnIconPrimary = "#fff"
colorRightColumnIconBackground = "#465484"
pages = 1
# Set this param to 'true' to swap the bar positions
swapColumns = false
